// <auto-generated />
namespace Delicious.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddUnitEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUnitEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "201806231337576_AddUnitEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
